global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: 'fastapi-churn'
    static_configs:
      - targets: ['fastapi-churn:5000']
    metrics_path: '/TrhBVe_m5gg2002_E5VVqS'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']