apiVersion: v1
kind: Service
metadata:
  name: fastapi-churn-service
spec:
  selector:
    app: fastapi-churn
  ports:
    - protocol: TCP
      port: 80          
      targetPort: 5000  
  type: LoadBalancer